import { randomUUID } from 'node:crypto';
import { mkdir, readFile, rename, stat, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

export interface ReliabilityPreflightSchedule { readonly enabled: boolean; readonly usualStreamTime: string; readonly leadMinutes: number; readonly daysOfWeek: readonly number[] }
interface ScheduleFile extends ReliabilityPreflightSchedule { readonly version: 1; readonly updatedAt: string }
interface PreflightReceipt { readonly ranAt: string; readonly scheduledFor: string; readonly ready: boolean; readonly readyChecks: number; readonly totalChecks: number; readonly summary: string }
const DEFAULT_SCHEDULE: ScheduleFile = { version: 1, enabled: false, usualStreamTime: '19:00', leadMinutes: 30, daysOfWeek: [0, 1, 2, 3, 4, 5, 6], updatedAt: new Date(0).toISOString() };

export class ScheduledReliabilityPreflightService {
  private readonly schedulePath: string; private readonly historyPath: string;
  private schedule: ScheduleFile = DEFAULT_SCHEDULE; private history: PreflightReceipt[] = []; private timer: NodeJS.Timeout | undefined; private running = false;
  public constructor(stateRoot: string, private readonly runPreflight: () => Promise<Readonly<Record<string, unknown>>>, private readonly now: () => Date = () => new Date()) { this.schedulePath = join(stateRoot, 'reliability-preflight-schedule.json'); this.historyPath = join(stateRoot, 'reliability-preflight-history.json'); }
  public async start(): Promise<void> { await Promise.all([this.loadSchedule(), this.loadHistory()]); this.timer = setInterval(() => void this.tick(), 60_000); this.timer.unref(); await this.tick(); }
  public stop(): void { if (this.timer !== undefined) clearInterval(this.timer); this.timer = undefined; }
  public status(): Readonly<Record<string, unknown>> { return { schedule: this.schedule, nextRunAt: this.nextRunAt(), history: [...this.history].reverse(), running: this.running, mutationFree: true }; }
  public async save(input: unknown): Promise<Readonly<Record<string, unknown>>> { const request = record(input); if (request['approvedByCreator'] !== true) throw new ScheduledPreflightError(403, 'Explicit creator approval is required to change the scheduled preflight.'); if (typeof request['enabled'] !== 'boolean') throw new ScheduledPreflightError(400, 'enabled must be true or false.'); const usualStreamTime = time(request['usualStreamTime']); const leadMinutes = integer(request['leadMinutes'], 'leadMinutes', 0, 360); const daysOfWeek = days(request['daysOfWeek']); this.schedule = { version: 1, enabled: request['enabled'], usualStreamTime, leadMinutes, daysOfWeek, updatedAt: this.now().toISOString() }; await atomicWrite(this.schedulePath, this.schedule); return this.status(); }
  public async runNow(): Promise<Readonly<Record<string, unknown>>> { const receipt = await this.execute(this.now().toISOString()); return { receipt, ...this.status() }; }
  private async tick(): Promise<void> { if (!this.schedule.enabled || this.running) return; const now = this.now(); const scheduledFor = scheduledCandidates(now, this.schedule, 1).find((candidate) => now.getTime() >= candidate.getTime() && now.getTime() - candidate.getTime() <= 90_000 && !this.history.some((entry) => entry.scheduledFor === candidate.toISOString())); if (scheduledFor === undefined) return; await this.execute(scheduledFor.toISOString()).catch(() => undefined); }
  private async execute(scheduledFor: string): Promise<PreflightReceipt> { this.running = true; try { const result = await this.runPreflight(); const checks = preflightChecks(result); const ready = result['ready'] === true; const receipt: PreflightReceipt = { ranAt: this.now().toISOString(), scheduledFor, ready, readyChecks: checks.filter((check) => check).length, totalChecks: checks.length, summary: ready ? 'Scheduled dry-run preflight passed.' : 'Scheduled dry-run preflight needs attention.' }; this.history = [...this.history, receipt].slice(-30); await atomicWrite(this.historyPath, this.history); return receipt; } finally { this.running = false; } }
  private nextRunAt(): string | undefined { if (!this.schedule.enabled) return undefined; const now = this.now(); return scheduledCandidates(now, this.schedule, 8).filter((candidate) => candidate.getTime() > now.getTime()).sort((left, right) => left.getTime() - right.getTime())[0]?.toISOString(); }
  private async loadSchedule(): Promise<void> { try { const detail = await stat(this.schedulePath); if (!detail.isFile() || detail.size > 32 * 1024) throw new Error('Scheduled preflight settings are invalid.'); const value = record(JSON.parse(await readFile(this.schedulePath, 'utf8')) as unknown); if (value['version'] !== 1) throw new Error('Scheduled preflight settings use an unsupported version.'); this.schedule = { version: 1, enabled: value['enabled'] === true, usualStreamTime: time(value['usualStreamTime']), leadMinutes: integer(value['leadMinutes'], 'leadMinutes', 0, 360), daysOfWeek: days(value['daysOfWeek']), updatedAt: typeof value['updatedAt'] === 'string' && Number.isFinite(Date.parse(value['updatedAt'])) ? value['updatedAt'] : new Date(0).toISOString() }; } catch (error) { if ((error as NodeJS.ErrnoException).code !== 'ENOENT') this.schedule = DEFAULT_SCHEDULE; } }
  private async loadHistory(): Promise<void> { try { const value = JSON.parse(await readFile(this.historyPath, 'utf8')) as unknown; if (Array.isArray(value)) this.history = value.flatMap(parseReceipt).slice(-30); } catch { this.history = []; } }
}
export class ScheduledPreflightError extends Error { public constructor(public readonly statusCode: number, message: string) { super(message); } }
function scheduledRunForDate(date: Date, schedule: ReliabilityPreflightSchedule): Date | undefined { if (!schedule.daysOfWeek.includes(date.getDay())) return undefined; const [hours = 0, minutes = 0] = schedule.usualStreamTime.split(':').map(Number); const result = new Date(date); result.setHours(hours, minutes - schedule.leadMinutes, 0, 0); return result; }
function scheduledCandidates(now: Date, schedule: ReliabilityPreflightSchedule, futureDays: number): Date[] { const candidates: Date[] = []; for (let offset = 0; offset <= futureDays; offset += 1) { const streamDate = new Date(now); streamDate.setDate(now.getDate() + offset); const candidate = scheduledRunForDate(streamDate, schedule); if (candidate !== undefined) candidates.push(candidate); } return candidates; }
function preflightChecks(result: Readonly<Record<string, unknown>>): boolean[] { const launcher = result['launcher']; const checks = launcher !== null && typeof launcher === 'object' && !Array.isArray(launcher) ? (launcher as Record<string, unknown>)['checks'] : []; return Array.isArray(checks) ? checks.map((check) => check !== null && typeof check === 'object' && !Array.isArray(check) && (check as Record<string, unknown>)['ready'] === true) : [result['ready'] === true]; }
function record(value: unknown): Record<string, unknown> { if (value === null || typeof value !== 'object' || Array.isArray(value)) throw new ScheduledPreflightError(400, 'Scheduled preflight request must be an object.'); return value as Record<string, unknown>; }
function time(value: unknown): string { if (typeof value !== 'string' || !/^(?:[01]\d|2[0-3]):[0-5]\d$/u.test(value)) throw new ScheduledPreflightError(400, 'usualStreamTime must use 24-hour HH:MM format.'); return value; }
function integer(value: unknown, label: string, minimum: number, maximum: number): number { if (!Number.isInteger(value) || (value as number) < minimum || (value as number) > maximum) throw new ScheduledPreflightError(400, `${label} must be an integer from ${String(minimum)} through ${String(maximum)}.`); return value as number; }
function days(value: unknown): number[] { if (!Array.isArray(value) || value.length === 0 || value.some((item) => !Number.isInteger(item) || item < 0 || item > 6)) throw new ScheduledPreflightError(400, 'Choose at least one valid day of week.'); return [...new Set(value as number[])].sort((left, right) => left - right); }
function parseReceipt(value: unknown): PreflightReceipt[] { if (value === null || typeof value !== 'object' || Array.isArray(value)) return []; const item = value as Record<string, unknown>; if (typeof item['ranAt'] !== 'string' || typeof item['scheduledFor'] !== 'string' || !Number.isFinite(Date.parse(item['ranAt'])) || !Number.isFinite(Date.parse(item['scheduledFor'])) || typeof item['ready'] !== 'boolean' || !Number.isInteger(item['readyChecks']) || !Number.isInteger(item['totalChecks']) || typeof item['summary'] !== 'string') return []; return [{ ranAt: item['ranAt'], scheduledFor: item['scheduledFor'], ready: item['ready'], readyChecks: item['readyChecks'] as number, totalChecks: item['totalChecks'] as number, summary: item['summary'].slice(0, 160) }]; }
async function atomicWrite(path: string, value: unknown): Promise<void> { await mkdir(dirname(path), { recursive: true }); const temporary = `${path}.${randomUUID()}.tmp`; await writeFile(temporary, `${JSON.stringify(value, null, 2)}\n`, { encoding: 'utf8', mode: 0o600 }); await rename(temporary, path); }
