const state={token:'',overview:null,draft:null,filters:null,commandBatch:[],lastGeneratedCommands:[]};
const byId=(id)=>document.getElementById(id);
async function api(path,options={}){const response=await fetch(path,{...options,headers:{authorization:`Bearer ${state.token}`,...options.headers}});const body=await response.json();if(!response.ok)throw new Error(body.error||`Request failed (${response.status})`);return body}
function safe(value){return String(value??'').replace(/[&<>"']/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function items(target,values,kind){byId(target).innerHTML=values.length?values.map((value)=>`<article class="item ${value.owned?'owned':''}"><strong>${safe(value.name)}</strong><small>${safe(kind==='action'?value.group:'')} ${safe(value.id)}</small><small>${value.enabled?'Enabled':'Disabled'}</small></article>`).join(''):'<p class="notice">None reported.</p>'}
function renderOverview(){const value=state.overview;byId('overview-cards').innerHTML=[['Mode',value.mode],['Platforms',Object.keys(value.configuration.platforms).length],['Blocker rules',value.configuration.filters.rules.length],['Preview',value.version]].map(([label,data])=>`<div class="stat"><span>${safe(label)}</span><strong>${safe(data)}</strong></div>`).join('');byId('ownership').innerHTML=value.ownership.map((item)=>`<article class="item owned"><strong>${safe(item.name)}</strong><small>${safe(item.kind)} · ${safe(item.packageId)} · ${safe(item.id)}</small></article>`).join('');state.filters=structuredClone(value.configuration.filters);renderPlatforms();renderFilters()}
function renderPlatforms(){const reports=new Map(state.overview.configuration.capabilities.map((report)=>[report.platform,report]));byId('platform-list').innerHTML=Object.entries(state.overview.configuration.platforms).map(([id,platform])=>{const report=reports.get(id);const supported=report?Object.entries(report.capabilities).filter(([,value])=>value.supported).map(([name])=>name).join(', '):'No provider declaration';return `<article class="item platform" data-platform="${safe(id)}"><div><strong>${safe(id)}</strong><small>${safe(platform.adapter)}</small></div><label><input type="checkbox" data-flag="enabled" ${platform.enabled?'checked':''}> Platform enabled</label><label><input type="checkbox" data-flag="inputEnabled" ${platform.inputEnabled?'checked':''}> Input enabled</label><label><input type="checkbox" data-flag="outputEnabled" ${platform.outputEnabled?'checked':''}> Output enabled</label><small>Provider capabilities: ${safe(supported||'none')}</small>${report?.limitations?.length?`<small>Limits: ${safe(report.limitations.join(' '))}</small>`:''}</article>`}).join('');document.querySelectorAll('.platform input').forEach((input)=>input.addEventListener('change',stagePlatform))}
function renderCommandSync(result){byId('command-sync-list').innerHTML=result.commands.length?result.commands.map((command)=>`<article class="item drift-${safe(command.driftStatus)}"><strong>${safe(command.name)}</strong><small>${safe(command.source)} · ${safe(command.streamerBotId)}</small><small>${safe(command.driftStatus)} · last seen ${safe(new Date(command.lastSeenAt).toLocaleString())}</small></article>`).join(''):'<p class="notice">No commands are tracked yet.</p>'}
function downloadGeneratedPackage(filename,contentBase64){const blob=new Blob([contentBase64],{type:'application/octet-stream'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=filename;link.click();URL.revokeObjectURL(url)}
function renderCommandBatch(){const list=byId('command-batch-list');list.innerHTML=state.commandBatch.length?state.commandBatch.map((design,index)=>`<article class="item"><strong>${safe(design.name)}</strong><small>${design.aliases.length?`aliases: ${safe(design.aliases.join(', '))} · `:''}${safe(design.minimumRole)}</small><button class="danger" data-remove-batch="${index}">Remove</button></article>`).join(''):'';byId('command-batch-state').textContent=state.commandBatch.length?`${state.commandBatch.length} command(s) queued.`:'No commands queued yet.';document.querySelectorAll('[data-remove-batch]').forEach((button)=>button.addEventListener('click',()=>{state.commandBatch.splice(Number(button.dataset.removeBatch),1);renderCommandBatch()}));byId('generate-batch').disabled=state.commandBatch.length===0||!byId('approve-batch').checked}
function renderCommandGeneration(result){const box=byId('command-generation-result');if(result.collisions?.length){box.innerHTML=result.collisions.map((collision)=>`<p class="notice">Design ${safe(collision.designIndex+1)}: "${safe(collision.matchedOn)}" already matches a live ${safe(collision.kind)} named "${safe(collision.name)}" (${safe(collision.id)}). Choose a different name or alias.</p>`).join('');state.lastGeneratedCommands=[];return}if(result.package){state.lastGeneratedCommands=result.package.commands.map((command,index)=>({commandId:command.commandId,name:command.name,aliases:result.designs[index]?.aliases||[]}));box.innerHTML=`<p class="notice">Generated <code>${safe(result.package.filename)}</code> with ${safe(result.package.commands.length)} command(s).</p>${result.package.commands.map((command)=>`<article class="item"><strong>${safe(command.name)}</strong><small>command ID ${safe(command.commandId)}</small></article>`).join('')}<button id="download-generated">Download package</button> <button id="verify-generated">Verify import</button>`;byId('download-generated').addEventListener('click',()=>downloadGeneratedPackage(result.package.filename,result.package.contentBase64));byId('verify-generated').addEventListener('click',verifyGeneratedCommands);return}box.innerHTML=''}
async function verifyGeneratedCommands(){if(!state.lastGeneratedCommands.length)return;const status=byId('command-generation-state');status.setAttribute('aria-busy','true');status.textContent='Verifying import against a fresh inspection…';try{const result=await api('/wizard/api/commands/verify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({commands:state.lastGeneratedCommands})});status.textContent=result.available?`Verified ${result.verifiedCommandIds.length} of ${state.lastGeneratedCommands.length} command(s). ${result.notFoundCommandIds.length} not found yet — import, bind, and enable those, then verify again.`:`Verification unavailable: ${result.error}`;if(result.commands)renderCommandSync({commands:result.commands})}catch(error){status.textContent=error.message}finally{status.removeAttribute('aria-busy')}}
function renderFilters(){const now=Date.now();byId('filter-list').innerHTML=state.filters.rules.length?state.filters.rules.map((rule)=>{const expired=rule.expiresAt&&Date.parse(rule.expiresAt)<=now;return `<article class="item ${rule.enabled&&!expired?'':'muted'}"><strong>${safe(rule.name)}</strong><small>${safe(rule.scope)} · ${safe(rule.target)} · ${safe(rule.match.kind)} “${safe(rule.match.value)}”</small><small>${rule.enabled?'Enabled':'Disabled'}${rule.expiresAt?` · ${expired?'expired':'expires'} ${safe(new Date(rule.expiresAt).toLocaleString())}`:''}</small><button data-toggle-rule="${safe(rule.id)}">${rule.enabled?'Disable':'Enable'}</button> <button class="danger" data-delete-rule="${safe(rule.id)}">Delete</button></article>`}).join(''):'<p class="notice">No blocker rules configured.</p>';document.querySelectorAll('[data-delete-rule]').forEach((button)=>button.addEventListener('click',async()=>{state.filters.rules=state.filters.rules.filter((rule)=>rule.id!==button.dataset.deleteRule);await stageFilters();renderFilters()}));document.querySelectorAll('[data-toggle-rule]').forEach((button)=>button.addEventListener('click',async()=>{state.filters.rules=state.filters.rules.map((rule)=>rule.id===button.dataset.toggleRule?{...rule,enabled:!rule.enabled}:rule);await stageFilters();renderFilters()}))}
async function ensureDraft(){if(state.draft?.status==='draft')return state.draft;state.draft=await api('/wizard/api/transactions',{method:'POST'});renderDraft();return state.draft}
function renderDraft(message=''){byId('transaction-state').textContent=message||(state.draft?`Draft ${state.draft.id}: ${state.draft.stagedChanges.length} staged change(s).`:'No configuration draft is active.');byId('commit').disabled=!state.draft||state.draft.stagedChanges.length===0;byId('cancel').disabled=!state.draft}
async function stagePlatform(event){try{const card=event.target.closest('[data-platform]');const values=Object.fromEntries([...card.querySelectorAll('input[data-flag]')].map((input)=>[input.dataset.flag,input.checked]));const draft=await ensureDraft();state.draft=await api(`/wizard/api/transactions/${draft.id}/stage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind:'platform',platform:card.dataset.platform,...values})});renderDraft()}catch(error){renderDraft(error.message)}}
async function stageFilters(){const draft=await ensureDraft();state.draft=await api(`/wizard/api/transactions/${draft.id}/stage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind:'filters',filters:state.filters})});renderDraft()}
byId('login-form').addEventListener('submit',async(event)=>{event.preventDefault();state.token=byId('token').value.trim();byId('login-error').textContent='';try{state.overview=await api('/wizard/api/overview');renderOverview();byId('login').classList.add('hidden');byId('workspace').classList.remove('hidden');byId('mode').textContent='Authenticated · configuration mode'}catch(error){state.token='';byId('login-error').textContent=error.message}});
document.querySelectorAll('[data-view]').forEach((button)=>button.addEventListener('click',()=>{document.querySelectorAll('[data-view]').forEach((item)=>item.classList.toggle('active',item===button));document.querySelectorAll('[data-panel]').forEach((panel)=>panel.classList.toggle('hidden',panel.dataset.panel!==button.dataset.view))}));
byId('lock').addEventListener('click',()=>{state.token='';state.overview=null;state.draft=null;byId('token').value='';byId('workspace').classList.add('hidden');byId('login').classList.remove('hidden');byId('mode').textContent='Locked'});
byId('inspect').addEventListener('click',async()=>{const button=byId('inspect');const status=byId('inspection-state');button.disabled=true;status.setAttribute('aria-busy','true');status.textContent='Inspecting with GetActions and GetCommands…';try{const result=await api('/wizard/api/inspect',{method:'POST'});status.textContent=result.available?`Inspection completed ${new Date(result.inspectedAt).toLocaleString()}. ${result.requests.length} audited read requests.`:`Inspection unavailable: ${result.error}`;items('actions',result.actions,'action');items('commands',result.commands,'command')}catch(error){status.textContent=error.message}finally{status.removeAttribute('aria-busy');button.disabled=false}});
byId('add-filter').addEventListener('submit',async(event)=>{event.preventDefault();const data=new FormData(event.target);const id=String(data.get('name')).trim().toLowerCase().replace(/[^a-z0-9-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,50)||`rule-${Date.now()}`;if(state.filters.rules.some((rule)=>rule.id===id)){byId('filter-state').textContent='Use a unique rule name.';return}const scope=String(data.get('scope'));const expiresAtLocal=String(data.get('expiresAt')||'');state.filters.rules.push({id,name:String(data.get('name')).trim(),enabled:data.get('enabled')==='on',scope,moduleIds:scope==='module'?String(data.get('moduleIds')).split(',').map((value)=>value.trim()).filter(Boolean):[],platforms:String(data.get('platforms')).split(',').map((value)=>value.trim().toLowerCase()).filter(Boolean),actorTypes:[],target:String(data.get('target')),match:{kind:String(data.get('kind')),value:String(data.get('value')),caseSensitive:data.get('caseSensitive')==='on'},...(expiresAtLocal?{expiresAt:new Date(expiresAtLocal).toISOString()}:{})});try{await stageFilters();renderFilters();event.target.reset();byId('filter-state').textContent='Rule staged. Commit the draft to save it.'}catch(error){state.filters.rules=state.filters.rules.filter((rule)=>rule.id!==id);byId('filter-state').textContent=error.message}});
byId('begin').addEventListener('click',async()=>{try{await ensureDraft()}catch(error){renderDraft(error.message)}});
byId('cancel').addEventListener('click',async()=>{if(!state.draft)return;try{state.draft=await api(`/wizard/api/transactions/${state.draft.id}/cancel`,{method:'POST'});state.overview=await api('/wizard/api/overview');state.draft=null;renderOverview();renderDraft('Draft cancelled; no configuration was changed.')}catch(error){renderDraft(error.message)}});
byId('commit').addEventListener('click',async()=>{if(!state.draft)return;try{const committed=await api(`/wizard/api/transactions/${state.draft.id}/commit`,{method:'POST'});state.draft=null;state.overview=await api('/wizard/api/overview');renderOverview();renderDraft(`Committed with backup ${committed.backupPath}. Restart StreamBridge to apply the settings.`)}catch(error){renderDraft(error.message)}});
byId('export-config').addEventListener('click',async()=>{try{byId('transfer').value=JSON.stringify(await api('/wizard/api/configuration/export'),null,2);byId('transfer-state').textContent='Safe configuration export created. Secrets are not included.'}catch(error){byId('transfer-state').textContent=error.message}});
byId('import-config').addEventListener('click',async()=>{try{const draft=await ensureDraft();state.draft=await api(`/wizard/api/transactions/${draft.id}/import`,{method:'POST',headers:{'content-type':'application/json'},body:byId('transfer').value});renderDraft();byId('transfer-state').textContent='Import staged. Review and commit to save it.'}catch(error){byId('transfer-state').textContent=error.message}});
byId('sync-commands').addEventListener('click',async()=>{const button=byId('sync-commands');const status=byId('command-sync-state');button.disabled=true;status.setAttribute('aria-busy','true');status.textContent='Syncing tracked commands against Streamer.bot…';try{const result=await api('/wizard/api/commands/sync',{method:'POST'});status.textContent=result.available?`Sync completed ${new Date(result.syncedAt).toLocaleString()}. ${result.commands.length} tracked command(s).`:`Sync unavailable: ${result.error}`;renderCommandSync(result)}catch(error){status.textContent=error.message}finally{status.removeAttribute('aria-busy');button.disabled=false}});
byId('design-command').addEventListener('submit',(event)=>{event.preventDefault();if(!event.target.checkValidity()){event.target.reportValidity();return}const data=new FormData(event.target);state.commandBatch.push({name:String(data.get('name')||''),aliases:String(data.get('aliases')||'').split(',').map((value)=>value.trim()).filter(Boolean),minimumRole:String(data.get('minimumRole')),note:String(data.get('note')||'')});event.target.reset();renderCommandBatch()});
byId('approve-batch').addEventListener('change',renderCommandBatch);
byId('generate-batch').addEventListener('click',async()=>{const status=byId('command-generation-state');status.setAttribute('aria-busy','true');status.textContent='Checking for collisions and generating…';try{const designs=state.commandBatch.map((design)=>({...design,approvedByCreator:true}));const result=await api('/wizard/api/commands/generate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({designs})});status.textContent=result.available?(result.collisions?.length?'Collision detected — see below.':'Package generated. Review it before importing.'):`Generation unavailable: ${result.error}`;renderCommandGeneration(result);if(result.package){state.commandBatch=[];byId('approve-batch').checked=false;renderCommandBatch()}}catch(error){status.textContent=error.message}finally{status.removeAttribute('aria-busy')}});
byId('refresh-diagnostics').addEventListener('click',async()=>{byId('diagnostics').textContent=JSON.stringify(await api('/wizard/api/diagnostics'),null,2)});
renderDraft();
