export const REWARD_PLATFORM_POLICY = Object.freeze({
  twitch: Object.freeze({ entry: 'native-channel-reward', redemption: 'supported', mutation: 'compile-verified-live-pending', refund: 'supported-when-queued', note: 'Use Streamer.bot-owned custom rewards. Keep the Twitch reward queue enabled whenever an add-on may reject and refund a claim.' }),
  kick: Object.freeze({ entry: 'native-channel-reward', redemption: 'supported', mutation: 'unsupported', refund: 'unsupported', note: 'Streamer.bot documents Kick redemption intake but no equivalent create, update, fulfill, or refund methods. Creator setup is manual.' }),
  youtube: Object.freeze({ entry: 'viewer-foundation-command', redemption: 'not-applicable', mutation: 'internal-only', refund: 'idempotent-internal-refund', note: 'YouTube uses Viewer Foundation points and a no-response command rather than pretending native rewards exist.' }),
  tiktok: Object.freeze({ entry: 'viewer-foundation-command', redemption: 'not-applicable', mutation: 'internal-only', refund: 'idempotent-internal-refund', note: 'TikTok uses Viewer Foundation points and a TikFinity-relayed no-response command.' }),
});

const shared = Object.freeze({ perUserCooldownSeconds: 0, maximumUsesPerStream: null, moderatorBypass: false });

export const REWARD_BLUEPRINTS = Object.freeze([
  Object.freeze({ ...shared, moduleId: 'thsv.fan-crown', internalId: 'fan-crown', title: 'Fan Crown', description: 'Claim the crown and become the stream current No. 1 Fan.', cost: 500, color: '#F2C94C', input: 'off', globalCooldownSeconds: 10, skippable: false, cancellable: true, refundOnFailure: true, coordination: 'queueable', twitchQueue: 'on' }),
  Object.freeze({ ...shared, moduleId: 'thsv.first-five', internalId: 'first-five-{place}', title: 'First Five: Claim {place}', description: 'Claim this First Five placement for the current stream.', cost: 100, color: '#2DB7A3', input: 'off', globalCooldownSeconds: 2, maximumUsesPerStream: 5, skippable: false, cancellable: true, refundOnFailure: true, coordination: 'queueable', twitchQueue: 'on' }),
  Object.freeze({ ...shared, moduleId: 'thsv.village-roll-call', internalId: 'village-roll-call', title: 'Village Roll Call', description: 'Check in once today and build your monthly village attendance.', cost: 50, color: '#2E8B57', input: 'off', globalCooldownSeconds: 2, perUserCooldownSeconds: 86_400, skippable: true, cancellable: false, refundOnFailure: false, coordination: 'independent', twitchQueue: 'off' }),
  Object.freeze({ ...shared, moduleId: 'thsv.viewer-spotlight', internalId: 'viewer-spotlight', title: 'Viewer Spotlight', description: 'Show your current viewer card on the stream overlay.', cost: 250, color: '#2DB7A3', input: 'off', globalCooldownSeconds: 10, skippable: true, cancellable: true, refundOnFailure: true, coordination: 'queueable', twitchQueue: 'on' }),
  Object.freeze({ ...shared, moduleId: 'thsv.voice-relay', internalId: 'village-voice', title: 'Village Voice - TTS', description: 'Enter a short message for the stream to read aloud. Safety filters and cooldowns apply.', cost: 500, color: '#7C3AED', input: 'required', globalCooldownSeconds: 10, perUserCooldownSeconds: 60, skippable: true, cancellable: true, refundOnFailure: true, coordination: 'queueable', twitchQueue: 'on' }),
  Object.freeze({ ...shared, moduleId: 'thsv.raid-scout', internalId: 'raid-scout-suggestion', title: 'Raid Scout Suggestion', description: 'Suggest one Twitch channel for tonight raid search.', cost: 500, color: '#F59E0B', input: 'required', globalCooldownSeconds: 15, skippable: true, cancellable: true, refundOnFailure: true, coordination: 'high-priority', twitchQueue: 'on' }),
  Object.freeze({ ...shared, moduleId: 'thsv.free-game-check', internalId: 'free-games', title: 'Free Games', description: 'Ask the stream to share the current free-game list and Discord destination.', cost: 100, color: '#2563EB', input: 'off', globalCooldownSeconds: 60, perUserCooldownSeconds: 300, skippable: true, cancellable: false, refundOnFailure: false, coordination: 'independent', twitchQueue: 'off' }),
]);
