import { afterEach, describe, expect, it, vi } from 'vitest';
/* eslint-disable @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access -- executable add-ons intentionally export plain JavaScript */
// @ts-expect-error executable add-on entrypoints are intentionally plain JavaScript
import chatPlay from '../../addons/chat-play-pack/dist/index.js';

function event(command:string,args:string[],moderator=false){return{schemaVersion:'1.0.0',eventId:`${command}-${args.join('-')}`,eventType:'command.received',platform:'youtube',receivedAt:new Date().toISOString(),user:{id:moderator?'mod':'viewer',name:moderator?'Mod':'Viewer',displayName:moderator?'Mod':'Viewer',actorType:'human',roles:moderator?['moderator']:[]},payload:{command,arguments:args},metadata:{simulated:false}};}
function contextFor(initial:Record<string,unknown>={},settings:Record<string,unknown>={}){let state=initial;return{context:{settings:{enabled:true,awardPoints:25,...settings},state:{read:vi.fn(async()=>state),write:vi.fn(async(value:Record<string,unknown>)=>{state=value;})},chat:{send:vi.fn(async()=>[])},overlay:{publish:vi.fn(async()=>{})},viewerFoundation:{getProjection:vi.fn(async()=>({viewerId:'viewer-abc'})),mutate:vi.fn(async()=>({}))}},state:()=>state};}
describe('Chat Play Pack',()=>{
  afterEach(()=>vi.restoreAllMocks());
  it('runs a number round and awards the winner idempotently through Viewer Foundation',async()=>{vi.spyOn(Math,'random').mockReturnValue(0);const holder=contextFor();await chatPlay.start(holder.context);await chatPlay.onEvent(event('play',['number','10'],true),holder.context);await chatPlay.onEvent(event('guess',['1']),holder.context);expect(holder.context.viewerFoundation.mutate).toHaveBeenCalledWith(expect.objectContaining({viewerId:'viewer-abc',operation:'add',amount:25,idempotencyKey:expect.any(String)}));expect(holder.context.overlay.publish).toHaveBeenCalledWith('thsv.chat-play-pack.result.show',expect.objectContaining({title:'Chat Play winner'}));await chatPlay.stop();});
  it('sanitizes corrupt persisted rounds and rejects duplicate prediction choices',async()=>{const holder=contextFor({round:{kind:'number',target:99,maximum:10,startedAt:1},roundSequence:-5,completedRounds:Number.MAX_SAFE_INTEGER});await chatPlay.start(holder.context);expect(holder.state()).toEqual({round:null,roundSequence:0,completedRounds:1_000_000_000});await chatPlay.onEvent(event('predict',['open','Best?','|','Same','|','same'],true),holder.context);expect(holder.state().round).toBeNull();expect(holder.context.chat.send).toHaveBeenCalledWith(expect.objectContaining({message:'Prediction choices must be different.'}));await chatPlay.stop();});
  it('keeps a round until the final live platform is offline and ignores simulated lifecycle events',async()=>{const holder=contextFor();await chatPlay.start(holder.context);await chatPlay.onEvent({...event('play',[],true),eventType:'stream.online',platform:'twitch'},holder.context);await chatPlay.onEvent({...event('play',[],true),eventType:'stream.online',platform:'youtube'},holder.context);await chatPlay.onEvent(event('play',['number','10'],true),holder.context);await chatPlay.onEvent({...event('play',[],true),eventType:'stream.offline',platform:'twitch',metadata:{simulated:true}},holder.context);expect(holder.state().round).not.toBeNull();await chatPlay.onEvent({...event('play',[],true),eventType:'stream.offline',platform:'twitch'},holder.context);expect(holder.state().round).not.toBeNull();await chatPlay.onEvent({...event('play',[],true),eventType:'stream.offline',platform:'youtube'},holder.context);expect(holder.state().round).toBeNull();await chatPlay.stop();});
  it('fails closed when command names collide',async()=>{const holder=contextFor({}, {playCommand:'game',guessCommand:'game'});await chatPlay.start(holder.context);await chatPlay.onEvent({...event('game',['number','10'],true),payload:{command:'game',arguments:['number','10']}},holder.context);expect(holder.context.chat.send).not.toHaveBeenCalled();expect(holder.state().round).toBeNull();await chatPlay.stop();});
});
