import { afterEach, describe, expect, it, vi } from 'vitest';
/* eslint-disable @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access -- executable add-ons intentionally export plain JavaScript */
// @ts-expect-error executable add-on entrypoints are intentionally plain JavaScript
import chatPlay from '../../addons/chat-play-pack/dist/index.js';

let sequence = 0;
function event(command:string,args:string[],moderator=false,user='viewer',displayName='Viewer'){sequence+=1;const suffix=args.length>0?` ${args.join(' ')}`:'';return{schemaVersion:'1.0.0',eventId:`event-${String(sequence)}-${command}`,eventType:'chat.message',platform:'youtube',receivedAt:new Date().toISOString(),user:{id:user,name:displayName,displayName,actorType:'human',roles:moderator?['moderator']:[]},payload:{message:`!${command}${suffix}`},metadata:{simulated:false}};}
function chat(user:string,displayName:string){sequence+=1;return{...event('',[],false,user,displayName),eventId:`chat-${String(sequence)}`,eventType:'chat.message',payload:{message:'hello'}};}
function contextFor(initial:Record<string,unknown>={},settings:Record<string,unknown>={}){let state=initial;const projection=vi.fn(async(query?:Record<string,unknown>)=>({viewerId:query?.userId==='target-user'?'viewer-target':'viewer-abc'}));return{context:{settings:{enabled:true,awardPoints:25,...settings},state:{read:vi.fn(async()=>state),write:vi.fn(async(value:Record<string,unknown>)=>{state=value;})},chat:{send:vi.fn(async()=>[])},overlay:{publish:vi.fn(async()=>{})},streamerbot:{runApprovedAction:vi.fn(async()=>({dispatched:true}))},viewerFoundation:{getProjection:projection,mutate:vi.fn(async()=>({}))}},state:()=>state};}

describe('Chat Play Pack',()=>{
  afterEach(()=>{vi.restoreAllMocks();sequence=0;});

  it('runs a number round and awards the winner idempotently through Viewer Foundation',async()=>{const holder=contextFor();await chatPlay.start(holder.context);await chatPlay.onEvent(event('play',['number','10'],true),holder.context);const target=(holder.state()['round'] as {target:number}).target;await chatPlay.onEvent(event('guess',[String(target)]),holder.context);expect(holder.context.viewerFoundation.mutate).toHaveBeenCalledWith(expect.objectContaining({viewerId:'viewer-abc',operation:'add',amount:25,idempotencyKey:expect.any(String)}));expect(holder.context.overlay.publish).toHaveBeenCalledWith('thsv.chat-play-pack.result.show',expect.objectContaining({title:'Number Guess winner'}));await chatPlay.stop();});

  it('uses public intake chat once and ignores its derived NormalizedCommand copy',async()=>{const holder=contextFor({}, {coinFlipEnabled:true});await chatPlay.start(holder.context);await chatPlay.onEvent(event('coinflip',['heads']),holder.context);expect(holder.context.chat.send).toHaveBeenCalledTimes(1);await chatPlay.onEvent({schemaVersion:'1.0.0',eventId:'derived-command',eventType:'command.received',platform:'youtube',receivedAt:new Date().toISOString(),source:{adapter:'bridge',eventId:'source-event',eventName:'NormalizedCommand'},user:{id:'viewer',name:'Viewer',displayName:'Viewer',actorType:'human',roles:[]},payload:{command:'coinflip',arguments:['heads']},metadata:{simulated:false}},holder.context);expect(holder.context.chat.send).toHaveBeenCalledTimes(1);await chatPlay.stop();});

  it('sanitizes corrupt persisted rounds and rejects duplicate prediction choices',async()=>{const holder=contextFor({round:{kind:'number',target:99,maximum:10,startedAt:1},roundSequence:-5,completedRounds:Number.MAX_SAFE_INTEGER});await chatPlay.start(holder.context);expect(holder.state()).toMatchObject({round:null,roundSequence:0,completedRounds:1_000_000_000,duels:[],awardLog:[],apiTrivia:[],apiUnscramble:[]});await chatPlay.onEvent(event('predict',['open','Best?','|','Same','|','same'],true),holder.context);expect(holder.state().round).toBeNull();expect(holder.context.chat.send).toHaveBeenCalledWith(expect.objectContaining({message:'Prediction choices must be different.'}));await chatPlay.stop();});

  it('accepts creator trivia answers without case, punctuation, or spacing sensitivity',async()=>{const holder=contextFor({}, {triviaQuestions:['Capital of France? | Paris | Paris, France'],triviaPoints:30});await chatPlay.start(holder.context);await chatPlay.onEvent(event('play',['trivia'],true),holder.context);await chatPlay.onEvent(event('answer',['  PARIS!!!  ']),holder.context);expect(holder.context.viewerFoundation.mutate).toHaveBeenCalledWith(expect.objectContaining({amount:30,reason:'Chat Play Trivia winner'}));expect(holder.state().round).toBeNull();await chatPlay.stop();});

  it('starts with built-in fallback content when saved creator lists are empty',async()=>{const holder=contextFor({}, {triviaSource:'creator',triviaQuestions:[],unscrambleEnabled:true,unscrambleSource:'creator',unscrambleWords:[]});await chatPlay.start(holder.context);await chatPlay.onEvent(event('play',['trivia'],true),holder.context);expect(holder.state().round).toMatchObject({kind:'trivia'});await chatPlay.onEvent(event('play',['stop'],true),holder.context);await chatPlay.onEvent(event('play',['unscramble'],true),holder.context);expect(holder.state().round).toMatchObject({kind:'unscramble'});await chatPlay.stop();});

  it('fetches a bounded OpenTDB batch, shuffles choices, and accepts only correct answers',async()=>{const holder=contextFor({}, {triviaSource:'opentdb',triviaQuestions:[]});await chatPlay.start(holder.context);await chatPlay.onEvent(event('play',['trivia'],true),holder.context);expect(holder.context.streamerbot.runApprovedAction).toHaveBeenCalledWith('d72d0873-8cbd-4dd5-a171-6b7122cd125e',expect.objectContaining({amount:10,category:'any'}));const requestId=(holder.state()['pendingTrivia'] as {requestId:string}).requestId;await chatPlay.onEvent({schemaVersion:'1.0.0',eventId:'relay-1',eventType:'addon.thsv.chat-play-pack.trivia-received',platform:'system',receivedAt:new Date().toISOString(),payload:{requestId,succeeded:true,questions:[{question:'What is 2 + 2?',answers:['4'],choices:['4','3','5'],category:'Math',difficulty:'easy'}]},metadata:{simulated:false}},holder.context);const round=holder.state()['round'] as {kind:string;question:string;choices:string[]};expect(round).toMatchObject({kind:'trivia',question:'What is 2 + 2?'});expect(new Set(round.choices)).toEqual(new Set(['4','3','5']));await chatPlay.onEvent(event('answer',['six']),holder.context);expect(holder.context.viewerFoundation.mutate).not.toHaveBeenCalled();expect(holder.state()['round']).not.toBeNull();const correctIndex=round.choices.indexOf('4')+1;await chatPlay.onEvent(event('answer',[String(correctIndex)]),holder.context);expect(holder.context.viewerFoundation.mutate).toHaveBeenCalled();await chatPlay.stop();});

  it('uses creator fallback when the optional OpenTDB action is unavailable',async()=>{const holder=contextFor({}, {triviaSource:'mixed',triviaQuestions:['Fallback question? | fallback']});holder.context.streamerbot.runApprovedAction.mockRejectedValue(new Error('not approved'));await chatPlay.start(holder.context);await chatPlay.onEvent(event('play',['trivia'],true),holder.context);expect(holder.state().round).toMatchObject({kind:'trivia',question:'Fallback question?'});expect(holder.context.streamerbot.runApprovedAction).toHaveBeenCalledOnce();await chatPlay.stop();});

  it('fetches and caches dictionary-backed unscramble words with definitions as hints',async()=>{const holder=contextFor({}, {unscrambleEnabled:true,unscrambleSource:'dictionary',unscrambleWords:[],dictionaryBatchSize:5,dictionaryMinimumLength:5,dictionaryMaximumLength:9});await chatPlay.start(holder.context);await chatPlay.onEvent(event('play',['unscramble'],true),holder.context);expect(holder.context.streamerbot.runApprovedAction).toHaveBeenCalledWith('08cf5035-09ce-45b7-bef5-c5f7081d17f6',expect.objectContaining({amount:5,minimumLength:5,maximumLength:9}));const requestId=(holder.state()['pendingUnscramble'] as {requestId:string}).requestId;await chatPlay.onEvent({schemaVersion:'1.0.0',eventId:'relay-words',eventType:'addon.thsv.chat-play-pack.unscramble-received',platform:'system',receivedAt:new Date().toISOString(),payload:{requestId,succeeded:true,words:[{word:'village',hint:'A small settlement.'},{word:'forest',hint:'A large area covered with trees.'}]},metadata:{simulated:false}},holder.context);const round=holder.state().round as {kind:string;answer:string;hint:string};expect(round.kind).toBe('unscramble');expect(['village','forest']).toContain(round.answer);expect(['A small settlement.','A large area covered with trees.']).toContain(round.hint);expect(holder.state().apiUnscramble).toHaveLength(1);expect(holder.context.chat.send).toHaveBeenLastCalledWith(expect.objectContaining({message:expect.stringContaining('Hint:')}));await chatPlay.stop();});

  it('uses the creator Unscramble list when the dictionary action is unavailable',async()=>{const holder=contextFor({}, {unscrambleEnabled:true,unscrambleSource:'mixed',unscrambleWords:['sloth | A slow-moving mammal']});holder.context.streamerbot.runApprovedAction.mockRejectedValue(new Error('not approved'));await chatPlay.start(holder.context);await chatPlay.onEvent(event('play',['unscramble'],true),holder.context);expect(holder.state().round).toMatchObject({kind:'unscramble',answer:'sloth',hint:'A slow-moving mammal'});expect(holder.context.streamerbot.runApprovedAction).toHaveBeenCalledOnce();await chatPlay.stop();});

  it('resolves accepted same-platform duels using stable Viewer Foundation identities',async()=>{const holder=contextFor({}, {duelEnabled:true});await chatPlay.start(holder.context);await chatPlay.onEvent(chat('target-user','Target Viewer'),holder.context);await chatPlay.onEvent(event('duel',['@Target Viewer'],false,'challenger-user','Challenger'),holder.context);expect(holder.state().duels).toHaveLength(1);await chatPlay.onEvent(event('accept',[],false,'target-user','Target Viewer'),holder.context);expect(holder.state().duels).toHaveLength(0);expect(holder.context.viewerFoundation.mutate).toHaveBeenCalledWith(expect.objectContaining({operation:'add',amount:20,reason:'Chat Play duel winner'}));await chatPlay.stop();});

  it('enforces the persistent hourly point cap across games',async()=>{const now=vi.spyOn(Date,'now').mockReturnValue(100_000);const holder=contextFor({awardLog:[{viewerId:'viewer-abc',at:99_000,amount:250}]},{maximumPointsPerViewerPerHour:250});await chatPlay.start(holder.context);await chatPlay.onEvent(event('play',['number','10'],true),holder.context);const target=(holder.state()['round'] as {target:number}).target;await chatPlay.onEvent(event('guess',[String(target)]),holder.context);expect(holder.context.viewerFoundation.mutate).not.toHaveBeenCalled();expect(holder.context.chat.send).toHaveBeenLastCalledWith(expect.objectContaining({message:expect.stringContaining('Hourly reward cap reached')}));now.mockRestore();await chatPlay.stop();});

  it('keeps a round until the final live platform is offline and ignores simulated lifecycle events',async()=>{const holder=contextFor();await chatPlay.start(holder.context);await chatPlay.onEvent({...event('play',[],true),eventType:'stream.online',platform:'twitch'},holder.context);await chatPlay.onEvent({...event('play',[],true),eventType:'stream.online',platform:'youtube'},holder.context);await chatPlay.onEvent(event('play',['number','10'],true),holder.context);await chatPlay.onEvent({...event('play',[],true),eventType:'stream.offline',platform:'twitch',metadata:{simulated:true}},holder.context);expect(holder.state().round).not.toBeNull();await chatPlay.onEvent({...event('play',[],true),eventType:'stream.offline',platform:'twitch'},holder.context);expect(holder.state().round).not.toBeNull();await chatPlay.onEvent({...event('play',[],true),eventType:'stream.offline',platform:'youtube'},holder.context);expect(holder.state().round).toBeNull();await chatPlay.stop();});

  it('fails closed when any configured command names collide',async()=>{const holder=contextFor({}, {playCommand:'game',guessCommand:'game'});await chatPlay.start(holder.context);await chatPlay.onEvent(event('game',['number','10'],true),holder.context);expect(holder.context.chat.send).not.toHaveBeenCalled();expect(holder.state().round).toBeNull();await chatPlay.stop();});
});
