import { readFile } from 'node:fs/promises';
import { gunzipSync } from 'node:zlib';
import { describe, expect, it } from 'vitest';
import { STREAMBRIDGE_VERSION } from '../../bridge/version.js';

describe('wizard launcher package', () => {
  it('contains author, description, reviewed source, and only a loopback wizard URL', async () => {
    const root = 'packages/streamerbot/wizard-launcher';
    const manifest = JSON.parse(await readFile(`${root}/manifest.json`, 'utf8')) as { name: string; version: string; author: string; description: string; action: { source: string; importFile: string } };
    expect(manifest).toMatchObject({ version: STREAMBRIDGE_VERSION, author: 'surakage' });
    expect(manifest.description.length).toBeGreaterThan(20);
    const source = await readFile(`${root}/${manifest.action.source}`, 'utf8');
    expect(source).toContain('open-wizard.mjs');
    expect(source).toContain('thsvBridgeInstallPath');
    expect(source).not.toMatch(/password|authorization/i);
    const encoded = (await readFile(`${root}/${manifest.action.importFile}`, 'utf8')).trim();
    const decoded = Buffer.from(encoded, 'base64');
    expect(decoded.subarray(0, 4).toString('ascii')).toBe('SBAE');
    const exported = JSON.parse(gunzipSync(decoded.subarray(4)).toString('utf8')) as { meta: { author: string; description: string }; data: { actions: Array<{ subActions: Array<{ byteCode?: string }> }> } };
    expect(exported.meta).toMatchObject({ author: manifest.author, description: manifest.description });
    const executeCode = exported.data.actions[0]?.subActions.find((subAction) => subAction.byteCode !== undefined)?.byteCode ?? '';
    expect(Buffer.from(executeCode, 'base64').toString('utf8').replaceAll('\r\n', '\n').trim()).toBe(source.replaceAll('\r\n', '\n').trim());
  });

  it('announces asynchronous results and supports a persistent system-aware color theme', async () => {
    const shell = await readFile('wizard/browser/index.html', 'utf8');
    const styles = await readFile('wizard/browser/styles.css', 'utf8');
    const script = await readFile('wizard/browser/app.js', 'utf8');
    const addOnScript = await readFile('wizard/browser/addons.js', 'utf8');
    const emotePreview = await readFile('wizard/browser/emote-preview.svg', 'utf8');
    expect(shell.match(/aria-live="polite"/g)).toHaveLength(20);
    expect(shell.match(/role="status"/g)).toHaveLength(19);
    expect(shell).toContain('id="wizard-feedback"');
    expect(shell).toContain('Open THSV Setup Wizard');
    expect(shell).toContain('Advanced recovery fallback only');
    expect(shell).toContain('THSV StreamBridge - Open Setup Wizard');
    expect(shell).toContain('id="download-recovery-key"');
    expect(shell).toContain('id="copy-control-token"');
    expect(shell).toContain('Do not share either one on stream.');
    expect(styles).toContain('.wizard-feedback[data-kind="success"]');
    expect(styles).toContain('.wizard-feedback[data-kind="warning"]');
    expect(script).toContain("warnings.length?'warning':'success'");
    expect(script).toContain('showWizardFeedback(`${action.label} completed.`');
    expect(script).toContain("fetch('/wizard/api/unlock'");
    expect(script).toContain("history.replaceState(null,'',`${location.pathname}${location.search}`)");
    expect(script).toContain("imageUrl:'/wizard/emote-preview.svg'");
    expect(styles).toContain('.preview-chat-emote');
    expect(emotePreview).toContain('Sample sloth emote');
    expect(addOnScript).toContain("button.textContent = 'Saving…'");
    expect(addOnScript).toContain("id === 'thsv.raid-scout' && settings.endBroadcastAfterRaid === true");
    expect(addOnScript).toContain("RAID_SCOUT_CONTROLLER_ACTION_ID, RAID_SCOUT_RUN_ENDING_AD_ACTION_ID, settings.endBroadcastActionId");
    expect(addOnScript).toContain('Settings and the selected Stop Streaming action grant were saved');
    expect(addOnScript).toContain("Choose an inspected Streamer.bot action...");
    expect(addOnScript).toContain("${safe(actionGroupName(action))} - ${safe(action.name)}");
    expect(addOnScript).not.toContain("Choose an inspected Streamer.bot actionâ€¦");
    expect(addOnScript).not.toContain("${safe(actionGroupName(action))} â€” ${safe(action.name)}");
    expect(styles).toContain('color-scheme:dark');
    expect(styles).toContain(':root[data-theme="light"]');
    expect(script).toContain("matchMedia('(prefers-color-scheme: light)')");
    expect(script).toContain("localStorage.setItem(themeStorageKey,next)");
    expect(script).toContain("link.download='THSV StreamBridge Recovery Key.txt'");
    expect(script).toContain('await navigator.clipboard.writeText(state.token)');
    expect(script).not.toContain('localStorage.setItem(\'control-token\'');
    expect(script).toContain("status.setAttribute('aria-busy','true')");
    expect(script).toContain("status.removeAttribute('aria-busy')");
    expect(script).toContain("kind==='command'&&value.managed");
    expect(script).toContain('data-admin-name');
    expect(script).toContain('THSV-managed command');
    expect(script).toContain("new Blob([contentBase64],{type:'text/plain;charset=utf-8'})");
    expect(script).not.toContain('atob(contentBase64)');
    expect(script).toContain("shoutoutTemplateOption.textContent='Automated Shoutouts — Multi-platform (features vary)'");
    expect(script).toContain("responseMode:'none',messages:{},note:'Automated Shoutouts owns");
    expect(script).toContain('<option value="viewer-card">Viewer Spotlight card — Multi-platform</option>');
    expect(script).toContain("'viewer-card':{name:'card',actionName:'THSV Command - Viewer Card'");
    expect(script).toContain("responseMode:'none',messages:{},note:'Viewer Spotlight owns");
    expect(script).toContain("'shoutout-basic'");
    expect(script).toContain("'commands-help':{name:'commands'");
    expect(shell).toContain('Available viewer commands');
    expect(script).toContain("api('/wizard/api/commands/directory')");
    expect(script).toContain("'/wizard/api/commands/directory/export'");
    expect(script).not.toContain('<option value="chat-play-control">');
    expect(script).not.toContain("'coin-flip':{name:'coinflip'");
    expect(script).not.toContain("'chat-play-control':{name:'play'");
    expect(script).not.toContain("'magic-8-ball':{name:'8ball'");
    expect(script).toContain("'game-suggestion':{name:'suggest'");
    expect(script).not.toContain("'random-joke':{name:'joke'");
    expect(script).not.toContain("hug:{name:'hug'");
    expect(script).toContain("'prize-wheel':{name:'spinwheel'");
    expect(script).not.toContain("'village-draw-info':{name:'giveaway'");
    expect(script).not.toContain("'village-draw-enter':{name:'enter'");
    expect(script).not.toContain("'village-draw-tickets':{name:'tickets'");
    expect(script).not.toContain("'village-draw-balance':{name:'mytickets'");
    expect(script).toContain("'viewer-points':{name:'points',actionName:'THSV Command - Viewer Points'");
    expect(script).toContain("'free-games':{name:'freegames',actionName:'THSV Command - Free Games'");
    expect(script).toContain("'custom-counter':{name:'streamcounter',actionName:'THSV Command - Custom Counter'");
    expect(script).not.toContain("'creator-poll':{name:'poll'");
    expect(script).not.toContain("'creator-vote':{name:'vote'");
    expect(script).toContain("'account-age':{name:'accountage'");
    expect(script).toContain("uptime:{name:'uptime'");
    expect(script).toContain("'follow-age':{name:'followage'");
    expect(script).toContain('https://api.twitch.tv/helix/users');
    expect(script).toContain('https://api.twitch.tv/helix/streams');
    expect(script).toContain('https://api.twitch.tv/helix/channels/followers');
    expect(script).toContain("commandSources:['twitch']");
    expect(script).toContain('thsv.command.game-suggestions.v1');
    expect(script).not.toContain('Game Suggestions.txt');
    expect(script).toContain('Lurk tracker — Multi-platform');
    expect(script).not.toContain('Hug leaderboard — Multi-platform');
    expect(script).toContain('Follow age — Twitch only');
    expect(script).toContain('thsv.command.lurk.v1.');
    expect(script).not.toContain('thsv.command.hugs.counts.v1');
    expect(script).toContain('TimeZoneInfo.Local');
    expect(script).toContain("for(const removedTemplate of ['rules','love','specs','emotes','bot'])");
    expect(addOnScript).toContain("addOn.moduleId === 'thsv.stream-labels'");
    expect(addOnScript).toContain("addOn.moduleId === 'thsv.village-roll-call'");
    expect(addOnScript).toContain("addOn.moduleId === 'thsv.prize-wheel'");
    expect(addOnScript).toContain("addOn.moduleId === 'thsv.village-polls'");
    expect(addOnScript).toContain('Last attempt:');
    expect(addOnScript).toContain('Next check:');
    expect(addOnScript).toContain('pollFollowerPulseUntilIdle');
    expect(addOnScript).toContain('Show exact template');
    expect(addOnScript).toContain('Hide preview');
    expect(addOnScript).toContain("action: 'hide'");
    expect(addOnScript).toContain('No separate Streamer.bot commands or poll triggers are needed');
    expect(addOnScript).toContain('Village Polls reads normalized chat directly');
    expect(addOnScript).toContain('Direct chat commands');
    expect(script).toContain('chatEventMinimalTemplates');
    expect(script).toContain('apply-chat-event-style');
    expect(script).toContain('alertMinimalTitles');
    expect(script).toContain('apply-alert-style');
    expect(script).toContain("'community-links':{id:'community-links'");
    expect(script).toContain("'rules-help':{id:'rules-help'");
    expect(script).toContain('{targetUrl}');
    expect(script).toContain('{channelUrl}');
    expect(script).not.toContain('Replace with their Twitch or social link.');
    expect(shell).toContain('Commands from enabled add-ons register automatically');
    expect(shell).toContain('You do not need separate Streamer.bot Command objects');
    expect(shell).toContain('data-panel="chat-overlay"');
    expect(shell).toContain('id="chat-dock-url"');
    expect(script).toContain("kind:'chat-overlay'");
    expect(script).toContain('showProfilePictures');
    expect(shell).toContain('Events in chat');
    expect(shell).toContain('Platform event limits');
    expect(script).toContain('eventLimitYoutube');
    expect(script).toContain('chatPlatformEventDefinitions');
    expect(script).toContain('events.platformEvents[platform]');
    expect(script).not.toContain("data.getAll('eventCategory')");
    expect(shell).not.toContain('Bits, donations, and Super Chats');
    expect(shell).toContain('data-panel="addons"');
    expect(addOnScript).toContain('/wizard/api/addons');
    expect(addOnScript).toContain('/wizard/api/addons/acceptance');
    expect(addOnScript).toContain('Published is not the same as provider accepted.');
    expect(addOnScript).toContain('not an operating-system sandbox');
    expect(addOnScript).toContain('/action-grants');
    expect(addOnScript).toContain('/overlay-preview');
    expect(addOnScript).toContain('/wizard/api/viewer-foundation/admin');
    expect(addOnScript).toContain('/wizard/api/community-analytics/admin');
    expect(addOnScript).toContain('/wizard/api/quote-vault/admin');
    expect(addOnScript).toContain('data-quote-vault-add-form');
    expect(addOnScript).toContain('broadcaster and moderator submissions are accepted automatically');
    expect(styles).toContain('.quote-vault-row');
    expect(addOnScript).toContain('/wizard/api/viewer-spotlight/admin');
    expect(addOnScript).toContain('data-spotlight-display-form');
    expect(addOnScript).toContain('data-spotlight-stream-score');
    expect(addOnScript).toContain('data-analytics-report');
    expect(addOnScript).toContain('Current community activity');
    expect(addOnScript).toContain('Recent streams');
    expect(addOnScript).toContain('All activity counters');
    expect(addOnScript).toContain('void refreshCommunityAnalyticsStatus()');
    expect(styles).toContain('.analytics-counter-grid');
    expect(addOnScript).toContain('data-viewer-correction-form');
    expect(addOnScript).toContain('data-viewer-search-account-form');
    expect(addOnScript).toContain('data-viewer-link-form');
    expect(addOnScript).toContain('data-viewer-undo-form');
    expect(addOnScript).toContain('Show recent administration history');
    expect(addOnScript).toContain('data-viewer-delete-form');
    expect(addOnScript).toContain('Why this is separate:');
    expect(addOnScript).toContain('Approve <strong>Create Clip</strong> and <strong>Deliver</strong> below');
    expect(addOnScript).toContain('No old-library posting:');
    expect(addOnScript).toContain('No add-on import needed');
    expect(addOnScript).toContain("addOn.moduleId === 'thsv.creator-controls'");
    expect(addOnScript).toContain('Connect your profile buttons');
    expect(addOnScript).toContain('Apply Profile 1</strong> &rarr; Starting Soon');
    expect(addOnScript).toContain('Keep Twitch, YouTube, Kick, and TikTok triggers attached');
    expect(addOnScript).toContain('!guardtrust');
    expect(addOnScript).toContain('data-chat-guard-incident-filters');
    expect(addOnScript).toContain('data-chat-guard-inline-review');
    expect(addOnScript).toContain('Download bounded report');
    expect(addOnScript).toContain('Chat text, names, and raw account IDs are never retained.');
    expect(addOnScript).toContain('addon-settings-section');
    expect(addOnScript).toContain('data-addon-enum-list');
    expect(addOnScript).toContain('data-addon-visible-field');
    expect(styles).toContain('.addon-toggle');
    expect(styles).toContain('.addon-choice-grid');
  });

  it('hosts add-on card and media overlays without package-controlled markup or unsafe URL protocols', async () => {
    const shell = await readFile('overlays/browser/addon-host.html', 'utf8');
    const script = await readFile('overlays/browser/addon-host.js', 'utf8');
    const styles = await readFile('overlays/browser/addon-host.css', 'utf8');
    expect(shell).toContain('/overlay/addons/host.js');
    expect(shell).toContain('/overlay/addons/host.css');
    expect(shell).toContain('id="timer-shell"');
    expect(script).toContain("event?.contractVersion !== 'thsv-addon-overlay-v1'");
    expect(script).toContain("url.protocol === 'https:' || url.origin === location.origin");
    expect(script).toContain("`${moduleId}.media.play`");
    expect(script).toContain("`${moduleId}.timer.update`");
    expect(script).toContain('safeColor(style.backgroundColor');
      expect(script).toContain("media.addEventListener('playing', () => {");
      expect(script).toContain('if (activePlaybackId === playbackId) return;');
      expect(script).toContain('rendererId, playbackId: activePlaybackId');
    expect(script).toContain("transportState('live');");
    expect(script).toContain("mediaShell.classList.add('fading')");
    expect(script).toContain('textContent');
    expect(script).not.toMatch(/innerHTML|insertAdjacentHTML|eval\(|new Function/u);
    expect(styles).toContain('object-fit: contain');
    expect(styles).toContain('transition: opacity .75s ease-in-out');
  });
});
