import { readFile } from 'node:fs/promises';
import { gunzipSync } from 'node:zlib';
import { describe, expect, it } from 'vitest';

describe('wizard launcher package', () => {
  it('contains author, description, reviewed source, and only a loopback wizard URL', async () => {
    const root = 'packages/streamerbot/wizard-launcher';
    const manifest = JSON.parse(await readFile(`${root}/manifest.json`, 'utf8')) as { name: string; version: string; author: string; description: string; action: { source: string; importFile: string } };
    expect(manifest).toMatchObject({ version: '2.4.0', author: 'surakage' });
    expect(manifest.description.length).toBeGreaterThan(20);
    const source = await readFile(`${root}/${manifest.action.source}`, 'utf8');
    expect(source).toContain('open-wizard.mjs');
    expect(source).toContain('thsvBridgeInstallPath');
    expect(source).not.toMatch(/password|authorization/i);
    const encoded = (await readFile(`${root}/${manifest.action.importFile}`, 'utf8')).trim();
    const decoded = Buffer.from(encoded, 'base64');
    expect(decoded.subarray(0, 4).toString('ascii')).toBe('SBAE');
    const exported = JSON.parse(gunzipSync(decoded.subarray(4)).toString('utf8')) as { meta: { author: string; description: string }; data: { actions: Array<{ subActions: Array<{ byteCode?: string }> }> } };
    expect(exported.meta).toMatchObject({ author: manifest.author, description: manifest.description });
    const executeCode = exported.data.actions[0]?.subActions.find((subAction) => subAction.byteCode !== undefined)?.byteCode ?? '';
    expect(Buffer.from(executeCode, 'base64').toString('utf8').replaceAll('\r\n', '\n').trim()).toBe(source.replaceAll('\r\n', '\n').trim());
  });

  it('announces asynchronous results and follows the operating-system color scheme', async () => {
    const shell = await readFile('wizard/browser/index.html', 'utf8');
    const styles = await readFile('wizard/browser/styles.css', 'utf8');
    const script = await readFile('wizard/browser/app.js', 'utf8');
    const addOnScript = await readFile('wizard/browser/addons.js', 'utf8');
    expect(shell.match(/aria-live="polite"/g)).toHaveLength(15);
    expect(shell.match(/role="status"/g)).toHaveLength(15);
    expect(styles).toContain('color-scheme:light dark');
    expect(styles).toContain('@media(prefers-color-scheme:light)');
    expect(script).toContain("status.setAttribute('aria-busy','true')");
    expect(script).toContain("status.removeAttribute('aria-busy')");
    expect(script).toContain("kind==='command'&&value.managed");
    expect(script).toContain('data-admin-name');
    expect(script).toContain('THSV-managed command');
    expect(shell).toContain('Reference role (not enforced)');
    expect(shell).toContain('Configure the real permission in Streamer.bot after import.');
    expect(shell).toContain('defaults to Twitch chat as its source');
    expect(shell).toContain('data-panel="chat-overlay"');
    expect(shell).toContain('id="chat-dock-url"');
    expect(script).toContain("kind:'chat-overlay'");
    expect(script).toContain('showProfilePictures');
    expect(shell).toContain('Events in chat');
    expect(shell).toContain('Platform event limits');
    expect(script).toContain('eventLimitYoutube');
    expect(script).toContain('chatPlatformEventDefinitions');
    expect(script).toContain('events.platformEvents[platform]');
    expect(script).not.toContain("data.getAll('eventCategory')");
    expect(shell).not.toContain('Bits, donations, and Super Chats');
    expect(shell).toContain('data-panel="addons"');
    expect(addOnScript).toContain('/wizard/api/addons');
    expect(addOnScript).toContain('not an operating-system sandbox');
    expect(addOnScript).toContain('/action-grants');
    expect(addOnScript).toContain('/overlay-preview');
    expect(addOnScript).toContain('addon-settings-section');
    expect(addOnScript).toContain('data-addon-enum-list');
    expect(addOnScript).toContain('data-addon-visible-field');
    expect(styles).toContain('.addon-toggle');
    expect(styles).toContain('.addon-choice-grid');
  });

  it('hosts add-on card and media overlays without package-controlled markup or unsafe URL protocols', async () => {
    const shell = await readFile('overlays/browser/addon-host.html', 'utf8');
    const script = await readFile('overlays/browser/addon-host.js', 'utf8');
    const styles = await readFile('overlays/browser/addon-host.css', 'utf8');
    expect(shell).toContain('/overlay/addons/host.js');
    expect(shell).toContain('/overlay/addons/host.css');
    expect(shell).toContain('id="timer-shell"');
    expect(script).toContain("event?.contractVersion !== 'thsv-addon-overlay-v1'");
    expect(script).toContain("url.protocol === 'https:' || url.origin === location.origin");
    expect(script).toContain("`${moduleId}.media.play`");
    expect(script).toContain("`${moduleId}.timer.update`");
    expect(script).toContain('safeColor(style.backgroundColor');
    expect(script).toContain("media.addEventListener('playing', () => {");
    expect(script).toContain("transportState('live');");
    expect(script).toContain("mediaShell.classList.add('fading')");
    expect(script).toContain('textContent');
    expect(script).not.toMatch(/innerHTML|insertAdjacentHTML|eval\(|new Function/u);
    expect(styles).toContain('object-fit: contain');
    expect(styles).toContain('transition: opacity 4s ease-in-out');
  });
});
